version: '3.8'

services:
  mysql:
    image: mysql:9.2
    ports:
      - '3306:3306'
    volumes:
      - mysqldata:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASS}
    command: --local-infile=1
    restart: unless-stopped

volumes:
  mysqldata:
